sudo: false
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "stable"
script:
  - node --version
  - npm --version
  # linting
  - npm run lint
  # nodejs testing
  - npm run test
  # browser testing
  - npm run browser
  # coverage report
  - npm run report
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
